"""Generate a small, runnable Express project from a validated plan."""

from __future__ import annotations

import json
from pathlib import Path

from agent.planner import GenerationPlan
from agent.specification import ArchitectureSpec


class GenerationError(ValueError):
    """Raised when generation would write outside the approved target directory."""


def _package_json(specification: ArchitectureSpec) -> str:
    package = {
        "name": specification.project_name,
        "version": "1.0.0",
        "private": True,
        "description": "Generated starter for the Space Fractions learning game.",
        "main": "src/app.js",
        "scripts": {"start": "node src/app.js", "test": "node --test"},
        "dependencies": {"express": "^4.21.2"},
    }
    return json.dumps(package, ensure_ascii=False, indent=2) + "\n"


def _app_js() -> str:
    return """const express = require(\"express\");
const { createGameRouter } = require(\"./routes/game\");

const app = express();
app.use(express.json());

app.get(\"/health\", (request, response) => {
  response.status(200).json({ status: \"ok\" });
});

app.use(createGameRouter());

app.use((request, response) => {
  response.status(404).json({ error: \"Route not found\" });
});

if (require.main === module) {
  const port = process.env.PORT || 3000;
  app.listen(port, () => {
    console.log(`Space Fractions API listening on port ${port}`);
  });
}

module.exports = app;
"""


def _game_router_js() -> str:
    return """const express = require(\"express\");
const {
  getQuestionForGame,
  evaluateAnswer,
} = require(\"../services/questionService\");

function createGameRouter() {
  const router = express.Router();

  router.get(\"/play\", (request, response) => {
    const gameId = 1;
    response.status(200).json({
      gameId,
      status: \"started\",
      question: getQuestionForGame(gameId),
    });
  });

  router.post(\"/play/:gameId/answer\", (request, response) => {
    const gameId = Number(request.params.gameId);
    const result = evaluateAnswer(gameId, request.body.answer);
    response.status(200).json({ gameId, ...result });
  });

  router.get(\"/scores/:gameId\", (request, response) => {
    response.status(200).json({
      gameId: Number(request.params.gameId),
      score: 0,
    });
  });

  return router;
}

module.exports = { createGameRouter };
"""


def _question_service_js() -> str:
    return """const { questions } = require(\"../data/questions\");

function getQuestionForGame(gameId) {
  const question = questions[(gameId - 1) % questions.length];
  return {
    id: question.id,
    prompt: question.prompt,
    options: question.options,
  };
}

function evaluateAnswer(gameId, answer) {
  const question = questions[(gameId - 1) % questions.length];
  return {
    correct: answer === question.answer,
    correctAnswer: question.answer,
  };
}

module.exports = { getQuestionForGame, evaluateAnswer };
"""


def _questions_js() -> str:
    return """const questions = [
  {
    id: \"fraction-1\",
    prompt: \"Which fraction is equal to one half?\",
    options: [\"1/2\", \"1/3\", \"2/3\", \"3/4\"],
    answer: \"1/2\",
  },
];

module.exports = { questions };
"""


def _test_js() -> str:
    return """const assert = require(\"node:assert/strict\");
const test = require(\"node:test\");
const app = require(\"../src/app\");

async function requestApplication(path) {
  const server = app.listen(0, \"127.0.0.1\");
  await new Promise((resolve) => server.once(\"listening\", resolve));

  try {
    const { port } = server.address();
    return await fetch(`http://127.0.0.1:${port}${path}`);
  } finally {
    await new Promise((resolve, reject) => {
      server.close((error) => (error ? reject(error) : resolve()));
    });
  }
}

test(\"GET /health reports a healthy service\", async () => {
  const response = await requestApplication(\"/health\");
  assert.equal(response.status, 200);
  assert.deepEqual(await response.json(), { status: \"ok\" });
});

test(\"GET /play starts a game and returns a fraction question\", async () => {
  const response = await requestApplication(\"/play\");
  const body = await response.json();
  assert.equal(response.status, 200);
  assert.equal(body.gameId, 1);
  assert.ok(body.question.prompt);
});
"""


def _readme(specification: ArchitectureSpec) -> str:
    components = "\n".join(f"- `{component}`" for component in specification.components)
    endpoints = "\n".join(
        f"- `{endpoint.method} {endpoint.path}` — {endpoint.summary}"
        for endpoint in specification.api_endpoints
    )
    requirements = "\n".join(f"- {requirement}" for requirement in specification.requirements)
    return f"""# Space Fractions

This project was generated by the Simple Architecture Code Agent from the supplied architecture documentation and PlantUML views.

## Architecture summary

- Project identifier: `{specification.project_name}`
- Architecture style: `{specification.architecture_style}`
- Runtime: `{specification.technology_stack.get("runtime", "Node.js")}`
- Web framework: `{specification.technology_stack.get("web_framework", "Express")}`

### Components

{components}

### Documented API

{endpoints}

### Traceability requirements

{requirements}

## Run locally

```bash
npm install
npm test
npm start
```

The API starts on `http://localhost:3000`. Try `GET /health` or `GET /play`.

## Docker

```bash
docker build -t space-fractions .
docker run --rm -p 3000:3000 space-fractions
```

## Generated files

- `architecture_spec.json` is the immutable architecture input used for this generation.
- `src/` contains an Express API with game and question responsibilities.
- `tests/app.test.js` is an HTTP-level Node.js test suite.
"""


def _dockerfile() -> str:
    return """FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY src ./src
EXPOSE 3000
CMD [\"npm\", \"start\"]
"""


TEMPLATES = {
    "src/app.js": _app_js,
    "src/routes/game.js": _game_router_js,
    "src/services/questionService.js": _question_service_js,
    "src/data/questions.js": _questions_js,
    "tests/app.test.js": _test_js,
    "Dockerfile": _dockerfile,
}


def _safe_destination(project_directory: Path, relative_path: str) -> Path:
    destination = (project_directory / relative_path).resolve()
    try:
        destination.relative_to(project_directory.resolve())
    except ValueError as error:
        raise GenerationError(f"Refusing to write outside project: {relative_path}") from error
    return destination


def _write_text(project_directory: Path, relative_path: str, content: str) -> None:
    destination = _safe_destination(project_directory, relative_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8")


def generate_project(
    specification: ArchitectureSpec, plan: GenerationPlan, output_directory: Path
) -> Path:
    """Generate every planned artifact and return the project directory."""
    project_directory = (output_directory / plan.target_directory).resolve()
    try:
        project_directory.relative_to(output_directory.resolve())
    except ValueError as error:
        raise GenerationError("The plan target must stay inside output/.") from error

    project_directory.mkdir(parents=True, exist_ok=True)
    _write_text(project_directory, "package.json", _package_json(specification))
    _write_text(project_directory, "README.md", _readme(specification))
    _write_text(project_directory, ".dockerignore", "node_modules\nnpm-debug.log\n.git\n")
    specification.write_json(_safe_destination(project_directory, "architecture_spec.json"))

    for relative_path, template in TEMPLATES.items():
        _write_text(project_directory, relative_path, template())

    generated_paths = {
        path.relative_to(project_directory).as_posix()
        for path in project_directory.rglob("*")
        if path.is_file()
    }
    planned_paths = {planned_file.path for planned_file in plan.files}
    missing_paths = planned_paths - generated_paths
    if missing_paths:
        raise GenerationError(f"Generator missed planned files: {sorted(missing_paths)}")
    return project_directory
